field.storage_settings.bricks_revisioned:
  type: field.storage_settings.entity_reference

field.field_settings.bricks_revisioned:
  type: field.field_settings.entity_reference

field.formatter.settings.bricks_nested:
  type: field.formatter.settings.entity_reference_revisions_entity_view

field.widget.settings.bricks_tree_autocomplete:
  type: field.widget.settings.entity_reference_autocomplete
